
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[0]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[1]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[2]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[3]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[4]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[5]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[6]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[7]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[8]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[9]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[10]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[11]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[12]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[13]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[14]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[15]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[16]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[17]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[18]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[19]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[20]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[21]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[22]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[23]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[24]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[25]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[26]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[27]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[28]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[29]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[30]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[5]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[0]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[1]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[2]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[3]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[4]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[5]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[6]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[7]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[8]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[9]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[10]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[11]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[12]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[13]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[14]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[15]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[16]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[17]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[18]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[19]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[20]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[21]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[22]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[23]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[24]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[25]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[26]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[27]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[28]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[29]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[30]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[2]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[0]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[1]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[2]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[3]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[4]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[5]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[6]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[7]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[8]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[9]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[10]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[11]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[12]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[13]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[14]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[15]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[16]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[17]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[18]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[19]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[20]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[21]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[22]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[23]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[24]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[25]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[26]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[27]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[28]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[29]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[30]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[6]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 4 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/write_pointer[0]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/write_pointer[1]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/write_pointer[2]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/write_pointer[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[0]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[1]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[2]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[3]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[4]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[5]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[6]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[7]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[8]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[9]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[10]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[11]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[12]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[13]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[14]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[15]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[16]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[17]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[18]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[19]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[20]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[21]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[22]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[23]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[24]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[25]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[26]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[27]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[28]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[29]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[30]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[1]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[0]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[1]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[2]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[3]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[4]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[5]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[6]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[7]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[8]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[9]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[10]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[11]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[12]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[13]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[14]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[15]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[16]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[17]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[18]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[19]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[20]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[21]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[22]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[23]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[24]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[25]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[26]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[27]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[28]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[29]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[30]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[9]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[0]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[1]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[2]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[3]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[4]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[5]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[6]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[7]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[8]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[9]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[10]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[11]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[12]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[13]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[14]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[15]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[16]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[17]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[18]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[19]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[20]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[21]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[22]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[23]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[24]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[25]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[26]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[27]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[28]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[29]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[30]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 2 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/mst_exec_state[0]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/mst_exec_state[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[0]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[1]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[2]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[3]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[4]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[5]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[6]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[7]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[8]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[9]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[10]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[11]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[12]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[13]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[14]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[15]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[16]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[17]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[18]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[19]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[20]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[21]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[22]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[23]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[24]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[25]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[26]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[27]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[28]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[29]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[30]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[8]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 4 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/read_pointer[0]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/read_pointer[1]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/read_pointer[2]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/read_pointer[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 4 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TSTRB[0]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TSTRB[1]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TSTRB[2]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TSTRB[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 32 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[0]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[1]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[2]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[3]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[4]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[5]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[6]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[7]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[8]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[9]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[10]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[11]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[12]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[13]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[14]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[15]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[16]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[17]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[18]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[19]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[20]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[21]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[22]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[23]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[24]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[25]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[26]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[27]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[28]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[29]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[30]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/AXIS_data[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 32 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[0]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[1]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[2]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[3]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[4]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[5]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[6]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[7]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[8]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[9]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[10]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[11]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[12]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[13]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[14]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[15]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[16]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[17]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[18]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[19]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[20]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[21]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[22]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[23]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[24]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[25]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[26]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[27]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[28]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[29]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[30]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[0]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 32 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[0]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[1]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[2]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[3]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[4]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[5]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[6]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[7]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[8]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[9]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[10]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[11]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[12]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[13]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[14]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[15]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[16]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[17]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[18]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[19]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[20]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[21]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[22]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[23]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[24]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[25]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[26]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[27]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[28]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[29]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[30]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[7]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 32 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[0]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[1]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[2]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[3]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[4]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[5]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[6]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[7]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[8]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[9]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[10]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[11]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[12]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[13]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[14]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[15]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[16]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[17]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[18]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[19]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[20]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[21]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[22]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[23]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[24]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[25]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[26]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[27]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[28]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[29]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[30]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[4]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 32 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[0]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[1]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[2]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[3]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[4]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[5]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[6]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[7]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[8]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[9]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[10]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[11]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[12]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[13]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[14]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[15]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[16]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[17]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[18]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[19]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[20]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[21]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[22]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[23]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[24]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[25]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[26]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[27]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[28]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[29]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[30]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/FIFO[3]__0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 32 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[0]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[1]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[2]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[3]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[4]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[5]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[6]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[7]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[8]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[9]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[10]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[11]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[12]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[13]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[14]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[15]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[16]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[17]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[18]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[19]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[20]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[21]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[22]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[23]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[24]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[25]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[26]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[27]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[28]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[29]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[30]} {design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/stream_data_out[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 2 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {design_1_i/axi_dma_0_M_AXI_S2MM_BRESP[0]} {design_1_i/axi_dma_0_M_AXI_S2MM_BRESP[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 4 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {design_1_i/KNN_accelerator_1_m00_axis_tstrb[0]} {design_1_i/KNN_accelerator_1_m00_axis_tstrb[1]} {design_1_i/KNN_accelerator_1_m00_axis_tstrb[2]} {design_1_i/KNN_accelerator_1_m00_axis_tstrb[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 32 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[0]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[1]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[2]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[3]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[4]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[5]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[6]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[7]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[8]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[9]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[10]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[11]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[12]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[13]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[14]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[15]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[16]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[17]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[18]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[19]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[20]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[21]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[22]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[23]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[24]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[25]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[26]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[27]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[28]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[29]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[30]} {design_1_i/axi_dma_0_M_AXI_S2MM_WDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 3 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {design_1_i/axi_dma_0_M_AXI_S2MM_AWSIZE[0]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWSIZE[1]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWSIZE[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 3 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {design_1_i/axi_dma_0_M_AXI_S2MM_AWPROT[0]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWPROT[1]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWPROT[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 32 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {design_1_i/KNN_accelerator_1_m00_axis_tdata[0]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[1]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[2]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[3]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[4]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[5]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[6]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[7]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[8]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[9]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[10]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[11]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[12]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[13]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[14]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[15]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[16]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[17]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[18]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[19]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[20]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[21]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[22]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[23]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[24]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[25]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[26]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[27]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[28]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[29]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[30]} {design_1_i/KNN_accelerator_1_m00_axis_tdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 2 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {design_1_i/axi_dma_0_M_AXI_S2MM_AWBURST[0]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWBURST[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 8 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {design_1_i/axi_dma_0_M_AXI_S2MM_AWLEN[0]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWLEN[1]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWLEN[2]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWLEN[3]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWLEN[4]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWLEN[5]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWLEN[6]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWLEN[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 4 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list {design_1_i/axi_dma_0_M_AXI_S2MM_WSTRB[0]} {design_1_i/axi_dma_0_M_AXI_S2MM_WSTRB[1]} {design_1_i/axi_dma_0_M_AXI_S2MM_WSTRB[2]} {design_1_i/axi_dma_0_M_AXI_S2MM_WSTRB[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 32 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[0]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[1]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[2]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[3]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[4]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[5]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[6]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[7]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[8]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[9]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[10]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[11]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[12]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[13]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[14]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[15]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[16]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[17]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[18]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[19]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[20]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[21]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[22]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[23]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[24]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[25]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[26]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[27]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[28]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[29]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[30]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWADDR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 4 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list {design_1_i/axi_dma_0_M_AXI_S2MM_AWCACHE[0]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWCACHE[1]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWCACHE[2]} {design_1_i/axi_dma_0_M_AXI_S2MM_AWCACHE[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 32 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[0]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[1]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[2]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[3]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[4]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[5]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[6]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[7]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[8]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[9]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[10]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[11]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[12]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[13]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[14]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[15]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[16]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[17]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[18]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[19]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[20]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[21]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[22]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[23]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[24]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[25]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[26]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[27]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[28]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[29]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[30]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataValueOut[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 32 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[0]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[1]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[2]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[3]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[4]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[5]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[6]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[7]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[8]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[9]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[10]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[11]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[12]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[13]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[14]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[15]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[16]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[17]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[18]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[19]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[20]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[21]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[22]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[23]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[24]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[25]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[26]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[27]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[28]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[29]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[30]} {design_1_i/KNN_accelerator_1/inst/knnTop/sort/dataNameOut[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list design_1_i/axi_dma_0_M_AXI_S2MM_AWREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list design_1_i/axi_dma_0_M_AXI_S2MM_AWVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list design_1_i/axi_dma_0_M_AXI_S2MM_BREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list design_1_i/axi_dma_0_M_AXI_S2MM_BVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list design_1_i/axi_dma_0_M_AXI_S2MM_WLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list design_1_i/axi_dma_0_M_AXI_S2MM_WREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list design_1_i/axi_dma_0_M_AXI_S2MM_WVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list design_1_i/axi_dma_0_s_axis_s2mm_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list design_1_i/KNN_accelerator_1/inst/knnTop/sort/AXIS_out_wr_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/axis_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/axis_tlast_delay]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/axis_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
connect_debug_port u_ila_0/probe42 [get_nets [list design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/axis_tvalid_delay]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
connect_debug_port u_ila_0/probe43 [get_nets [list design_1_i/KNN_accelerator_1_m00_axis_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe44]
set_property port_width 1 [get_debug_ports u_ila_0/probe44]
connect_debug_port u_ila_0/probe44 [get_nets [list design_1_i/KNN_accelerator_1_m00_axis_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe45]
set_property port_width 1 [get_debug_ports u_ila_0/probe45]
connect_debug_port u_ila_0/probe45 [get_nets [list design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_ARESETN]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe46]
set_property port_width 1 [get_debug_ports u_ila_0/probe46]
connect_debug_port u_ila_0/probe46 [get_nets [list design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe47]
set_property port_width 1 [get_debug_ports u_ila_0/probe47]
connect_debug_port u_ila_0/probe47 [get_nets [list design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe48]
set_property port_width 1 [get_debug_ports u_ila_0/probe48]
connect_debug_port u_ila_0/probe48 [get_nets [list design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe49]
set_property port_width 1 [get_debug_ports u_ila_0/probe49]
connect_debug_port u_ila_0/probe49 [get_nets [list design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/tx_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe50]
set_property port_width 1 [get_debug_ports u_ila_0/probe50]
connect_debug_port u_ila_0/probe50 [get_nets [list design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/tx_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe51]
set_property port_width 1 [get_debug_ports u_ila_0/probe51]
connect_debug_port u_ila_0/probe51 [get_nets [list design_1_i/KNN_accelerator_1/inst/KNN_accelerator_v3_0_M00_AXIS_inst/wr_en]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
